name: Test
on:
  pull_request:
  push:
jobs:

  Rust:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15]
        allow-fail: [false]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - uses: Swatinem/rust-cache@v1
      - run: nix-shell rust/shell.nix --run "cd rust && cargo test --color=always"

  Julia:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15]
        allow-fail: [false]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - uses: Swatinem/rust-cache@v1
      - run: nix-shell julia/shell.nix --run "cd julia && julia --color=yes testme.jl"

  Python:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15]
        py: [37, 38, 39]
        allow-fail: [false]
        include:
          - os: ubuntu-latest
            py: 310
            allow-fail: true
          - os: macos-10.15
            py: 310
            allow-fail: true
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - uses: Swatinem/rust-cache@v1
      - run: nix-shell python/shell.nix --run "cd python && pytest --color=yes -v"


# TODO Rust bindgen
# TODO Rust PyO3
# TODO home manager
# TODO C++ with clang support
